name: "final-project-compose"

services:

  # PostgreSQL
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: app-user
      POSTGRES_PASSWORD: app-password
      POSTGRES_DB: app-db
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app-user -d app-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Jaeger All-in-One
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # HTTP collector
      - "6831:6831/udp" # Jaeger agent (UDP)
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16686"]
      interval: 10s

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_volume:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_volume:/root/.ollama

volumes:
  postgres_volume:
  grafana_volume:
  ollama_volume:
